// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class tao2bangmoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tao2bangmoi));
        
        string IMigrationMetadata.Id
        {
            get { return "202103301132412_tao 2 bang moi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
