// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addcolummpaymenttoorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolummpaymenttoorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202104071155144_add columm payment to order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
