// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class edittableProduct2222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edittableProduct2222));
        
        string IMigrationMetadata.Id
        {
            get { return "202104140902016_edit table Product 2222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
