// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class editProductTSale3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editProductTSale3));
        
        string IMigrationMetadata.Id
        {
            get { return "202104230408489_edit ProductTSale3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
