// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addtabledistrictandProvince : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtabledistrictandProvince));
        
        string IMigrationMetadata.Id
        {
            get { return "202104050054029_add table district and Province"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
