// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class edituseroks28354 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edituseroks28354));
        
        string IMigrationMetadata.Id
        {
            get { return "202103300635085_edit useroks28354"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
